### PR TITLE
Add GitHub actions

### PR DESCRIPTION
**Pull request by JosephDuffy**
The tests are currently essentially empty but at a minimum this makes sure things compile on Xcode 11.7 and 12.0.

@shaps80 I think this will need updates to the repo settings to enable GitHub Actions.

### CODE REVIEW

**Comment by JosephDuffy** [comment]
Here's the setting that needs to be updated 

image

**Comment by shaps80** [comment]
I _think_ I've fixed it, check please :)

**Comment by JosephDuffy** [comment]
Looks to be good. I'll do a release after merge to test that too :)

**Comment by JosephDuffy** [comment]
@shaps80 Tests and releases are working. I thought the docs would publish to https://composed-swift.github.io/ComposedUI but maybe GitHub Pages needs to be setup for `gh-pages` branch in the settings.

Not a big deal but could be useful if you want to point people to the online docs.

**Pull request merged**
